### ISSUE TITLE
Some AZs are missing from the output, depending on the first account's visible AZ

### ISSUE THREAD

**Issue by ekuns** [MarkBiesheuvel/aws-cross-account-az-matching#3]
If the first account happens to only see a subset of the AZs in a region, and other accounts have a different subset of AZs, then some information will be missing in the output.  If you only care about the AZs visible to the first account, then you're not missing anything.  If you care about all AZs visible to all of the accounts, then you may be missing some of the information.

I'm not sure of an easy way to fix this, or else I would have provided a pull request.

**Comment by MarkBiesheuvel** [comment]
I think I was able to solve part of the issue. I've updated the script so it's agnostic to the account order.

However, some AZs are still not showing up. For example, us-west-1 only shows two AZs:
```
Mapping for region ap-northeast-1
+-----------------+---+---+---+
| xxxxxxxxxxxx    | a | c | d |
| xxxxxxxxxx      | a | c | d |
| xxxxxxxxxxxxx   | a | c | d |
| xxxxxxxxxxxxxxx | a | c | d |
| xxxxxxxxxxx     | a | c | d |
| xxxxxxxxxxxxx   | a | c | d |
| xxxxxxxxxx      | a | c | d |
| xxxxxxxxxxxxxxx | a | c | d |
| xxxxxxxxxxx     | a | c | d |
+-----------------+---+---+---+

Mapping for region us-west-1
+-----------------+---+---+
| xxxxxxxxxxxx    | a | c |
| xxxxxxxxxx      | b | a |
| xxxxxxxxxxxxx   | a | c |
| xxxxxxxxxxxxxxx | a | c |
| xxxxxxxxxxx     | b | a |
| xxxxxxxxxxxxx   | b | a |
| xxxxxxxxxx      | b | a |
| xxxxxxxxxxxxxxx | c | b |
| xxxxxxxxxxx     | a | c |
+-----------------+---+---+
```
My suspension is that this is due to some reserved offerings not having an assigned AZ. For example, I saw that describe_reserved_instances_offerings API call will return 4 results ap-northeast-1 for fixed parameters. Same as the number of AZs, however, only three of the results will have the key AvailabilityZone set and one hasn't. My guess is that this is AZ b. Which doesn't show up now. This is captured on line 83:
```python
            if 'AvailabilityZone' in offering
```

Not sure if that part of the issue is fixable.
